### ISSUE TITLE
Does not work with python 3.10

### ISSUE THREAD

**Issue by joinemm** [MrMrRobat/aiopolly#3]
```
from aiopolly import Polly
  File "/home/join/sync/code/miso-bot/venv/lib/python3.10/site-packages/aiopolly/__init__.py", line 3, in <module>
    from . import types
  File "/home/join/sync/code/miso-bot/venv/lib/python3.10/site-packages/aiopolly/types/__init__.py", line 2, in <module>
    from .lexicon import Lexicon, LexiconAttribute, LexiconsList
  File "/home/join/sync/code/miso-bot/venv/lib/python3.10/site-packages/aiopolly/types/lexicon.py", line 5, in <module>
    from .params import LanguageCode, Alphabet, SpeechMarkTypes
  File "/home/join/sync/code/miso-bot/venv/lib/python3.10/site-packages/aiopolly/types/params.py", line 4, in <module>
    from ..utils.strenum import StrEnum
  File "/home/join/sync/code/miso-bot/venv/lib/python3.10/site-packages/aiopolly/utils/strenum.py", line 177, in <module>
    class StrEnum(BaseStrEnum, metaclass=StrEnumMeta):
  File "/home/join/sync/code/miso-bot/venv/lib/python3.10/site-packages/aiopolly/utils/strenum.py", line 137, in __new__
    new_class_dict[name] = value
  File "/usr/lib/python3.10/enum.py", line 98, in __setitem__
    if _is_private(self._cls_name, key):
AttributeError: '_EnumDict' object has no attribute '_cls_name'
```

**Comment by AayushSolanki** [comment]
is there any solution of this?

**Comment by Bobronium** [comment]
@AayushSolanki, of course! The problem seems to be caused by `StrEnum` relying too much on internals of stdlib `enum` module. Should be relatively easy to fix. 

I won't be working on this project in the nearest future, but will gladly accept PRs with bug & compatibility fixes.

If you want to be maintainer of this project, drop a comment here or create another issue. I would expect you to have existing open source projects available on PyPI.

You also might want to contribute Polly support into https://github.com/samuelcolvin/aioaws, which is likely going to be maintained better.
